# Generated by Django 4.0 on 2022-03-29 14:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("plant", "0001_initial"),
        ("product", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="plant_id",
            field=models.ForeignKey(
                blank=True,
                db_column="plant_id",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="products",
                to="plant.plant",
            ),
        ),
    ]