# Generated by Django 4.0 on 2022-03-25 13:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("product", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="product",
            options={"ordering": ["-created_at"]},
        ),
        migrations.RenameField(
            model_name="product",
            old_name="created",
            new_name="created_at",
        ),
        migrations.RenameField(
            model_name="product",
            old_name="updated",
            new_name="updated_at",
        ),
    ]
