# Generated by Django 4.0 on 2022-03-11 06:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('plant', '0001_initial'),
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productcategory',
            name='plant_id',
        ),
        migrations.AddField(
            model_name='product',
            name='plant_id',
            field=models.ForeignKey(db_column='plant_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='product', to='plant.plant'),
        ),
    ]
