# Generated by Django 4.0 on 2022-03-26 12:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("product", "0002_alter_product_options_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="product",
            name="plant_id",
        ),
        migrations.RemoveField(
            model_name="product",
            name="qty",
        ),
    ]
