# Generated by Django 4.0 on 2022-03-25 13:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="PlantCategory",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("category", models.CharField(max_length=45)),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Plant",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("image", models.CharField(blank=True, max_length=256, null=True)),
                ("botanical_name", models.CharField(blank=True, max_length=100, null=True)),
                ("english_name", models.CharField(blank=True, max_length=150, null=True)),
                ("general_name", models.CharField(blank=True, max_length=100, null=True)),
                ("type_name", models.CharField(blank=True, max_length=100, null=True)),
                ("origin", models.CharField(blank=True, max_length=100, null=True)),
                ("advise_info", models.CharField(blank=True, max_length=100, null=True)),
                ("image_link", models.CharField(blank=True, max_length=256, null=True)),
                ("height_info", models.IntegerField(blank=True, null=True)),
                ("width_info", models.IntegerField(blank=True, null=True)),
                ("leaftype_info", models.CharField(blank=True, max_length=100, null=True)),
                ("toxic_info", models.CharField(blank=True, max_length=100, null=True)),
                ("breeding_info", models.CharField(blank=True, max_length=100, null=True)),
                ("extraperiod_info", models.CharField(blank=True, max_length=100, null=True)),
                ("grow_level", models.CharField(blank=True, max_length=100, null=True)),
                ("growth_speed", models.CharField(blank=True, max_length=100, null=True)),
                ("growth_temp", models.CharField(blank=True, max_length=100, null=True)),
                ("lowest_temp", models.CharField(blank=True, max_length=100, null=True)),
                ("humidity", models.CharField(blank=True, max_length=100, null=True)),
                ("fertilizer_info", models.CharField(blank=True, max_length=100, null=True)),
                ("soil_info", models.CharField(blank=True, max_length=100, null=True)),
                ("water_spring", models.CharField(blank=True, max_length=100, null=True)),
                ("water_summer", models.CharField(blank=True, max_length=100, null=True)),
                ("water_fall", models.CharField(blank=True, max_length=100, null=True)),
                ("water_winter", models.CharField(blank=True, max_length=100, null=True)),
                ("insect_info", models.CharField(blank=True, max_length=256, null=True)),
                ("extragrow_info", models.CharField(blank=True, max_length=2000, null=True)),
                ("functional_info", models.CharField(blank=True, max_length=2000, null=True)),
                ("care_need", models.CharField(blank=True, max_length=100, null=True)),
                ("type", models.CharField(blank=True, max_length=100, null=True)),
                ("growth_type", models.CharField(blank=True, max_length=100, null=True)),
                ("indoor_garden", models.CharField(blank=True, max_length=100, null=True)),
                ("ecology", models.CharField(blank=True, max_length=100, null=True)),
                ("leaf_pattern", models.CharField(blank=True, max_length=100, null=True)),
                ("leaf_color", models.CharField(blank=True, max_length=100, null=True)),
                ("flower_season", models.CharField(blank=True, max_length=100, null=True)),
                ("flower_color", models.CharField(blank=True, max_length=100, null=True)),
                ("fluit_season", models.CharField(blank=True, max_length=100, null=True)),
                ("fluit_color", models.CharField(blank=True, max_length=100, null=True)),
                ("breeding_way", models.CharField(blank=True, max_length=100, null=True)),
                ("lux", models.CharField(blank=True, max_length=100, null=True)),
                ("location", models.CharField(blank=True, max_length=256, null=True)),
                (
                    "plant_category_id",
                    models.ForeignKey(
                        db_column="plant_category_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="plant",
                        to="plant.plantcategory",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
