# Generated by Django 4.0 on 2022-03-30 01:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("plant", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="plant",
            name="main_name",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
