# Generated by Django 4.0 on 2022-03-11 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("plant", "0002_alter_plant_extragrow_info"),
    ]

    operations = [
        migrations.AlterField(
            model_name="plant",
            name="location",
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
