# Generated by Django 4.0 on 2022-03-10 09:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("user", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Feed",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("image", models.CharField(max_length=256)),
                ("content", models.CharField(blank=True, max_length=500, null=True)),
                (
                    "user_id",
                    models.ForeignKey(
                        db_column="user_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="feed",
                        to="user.users",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="FeedLike",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("like", models.IntegerField()),
                (
                    "feed_id",
                    models.ForeignKey(
                        db_column="feed_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="feed_like",
                        to="feed.feed",
                    ),
                ),
                (
                    "user_id",
                    models.ForeignKey(
                        db_column="user_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="feed_like",
                        to="user.users",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="FeedComment",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("content", models.CharField(max_length=200)),
                (
                    "feed_id",
                    models.ForeignKey(
                        db_column="feed_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="feed_comment",
                        to="feed.feed",
                    ),
                ),
                (
                    "user_id",
                    models.ForeignKey(
                        db_column="user_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="feed_comment",
                        to="user.users",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="FeedBookmark",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("bookmark", models.IntegerField()),
                (
                    "feed_id",
                    models.ForeignKey(
                        db_column="feed_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="feed_bookmark",
                        to="feed.feed",
                    ),
                ),
                (
                    "user_id",
                    models.ForeignKey(
                        db_column="user_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="feed_bookmark",
                        to="user.users",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
