# Generated by Django 4.0.3 on 2022-03-30 16:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('feed', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='feedlike',
            name='user_id',
            field=models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, related_name='feed_like', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='feedcomment',
            name='feed_id',
            field=models.ForeignKey(db_column='feed_id', on_delete=django.db.models.deletion.CASCADE, related_name='feed_comment', to='feed.feed'),
        ),
        migrations.AddField(
            model_name='feedcomment',
            name='user_id',
            field=models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, related_name='feed_comment', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='feedbookmark',
            name='feed_id',
            field=models.ForeignKey(db_column='feed_id', on_delete=django.db.models.deletion.CASCADE, related_name='feed_bookmark', to='feed.feed'),
        ),
        migrations.AddField(
            model_name='feedbookmark',
            name='user_id',
            field=models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, related_name='feed_bookmark', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='feed',
            name='user_id',
            field=models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, related_name='feed', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddConstraint(
            model_name='feedlike',
            constraint=models.UniqueConstraint(fields=('user_id', 'feed_id'), name='unique_user_feedlike'),
        ),
        migrations.AddConstraint(
            model_name='feedbookmark',
            constraint=models.UniqueConstraint(fields=('user_id', 'feed_id'), name='unique_user_feedbookmark'),
        ),
    ]
