# Generated by Django 4.0 on 2022-04-03 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feed',
            name='content',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
