# Generated by Django 4.0 on 2022-03-15 04:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("feed", "0004_feed_like_count"),
    ]

    operations = [
        migrations.CreateModel(
            name="Img",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("img", models.ImageField(max_length=255, upload_to="feed/%Y%m%d")),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.AddField(
            model_name="feed",
            name="title",
            field=models.CharField(default="", max_length=100),
            preserve_default=False,
        ),
    ]
