# Generated by Django 4.0 on 2022-03-19 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("feed", "0005_img_feed_title"),
    ]

    operations = [
        migrations.AddField(
            model_name="feed",
            name="views",
            field=models.IntegerField(default=0),
        ),
    ]
