# Generated by Django 4.0 on 2022-03-25 13:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="UserImg",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("img", models.ImageField(max_length=255, upload_to="user/%Y%m%d")),
                ("user", models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to="user.users")),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
