# Generated by Django 4.0 on 2022-03-27 05:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0002_userimg"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="userimg",
            name="user",
        ),
    ]
