# Generated by Django 4.0 on 2022-04-02 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0003_alter_users_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="users",
            name="image",
            field=models.CharField(default="https://greendoorhope.s3.amazonaws.com/img/profile.jpg", max_length=256),
        ),
    ]
