# Generated by Django 4.0 on 2022-04-03 23:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0005_usersfav_result1_usersfav_result2_usersfav_result3"),
    ]

    operations = [
        migrations.AddField(
            model_name="usersfav",
            name="user_id",
            field=models.ForeignKey(
                db_column="user_id",
                default="",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="fav",
                to="user.users",
            ),
            preserve_default=False,
        ),
    ]
