# Generated by Django 4.0 on 2022-04-03 23:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0006_usersfav_user_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="usersfav",
            name="user_id",
            field=models.ForeignKey(
                db_column="user_id",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="fav",
                to="user.users",
                unique=True,
            ),
        ),
    ]
