# Generated by Django 4.0 on 2022-04-03 23:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0007_alter_usersfav_user_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="usersfav",
            name="user_id",
            field=models.OneToOneField(
                db_column="user_id", on_delete=django.db.models.deletion.CASCADE, related_name="fav", to="user.users"
            ),
        ),
    ]
