# Generated by Django 4.0 on 2022-04-03 21:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("survey", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Choice",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("content", models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="Level",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name="Question",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("number", models.IntegerField(unique=True)),
                ("content", models.CharField(max_length=100)),
            ],
        ),
        migrations.DeleteModel(
            name="Answer",
        ),
        migrations.DeleteModel(
            name="Survey",
        ),
        migrations.AddField(
            model_name="choice",
            name="level",
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to="survey.level"),
        ),
        migrations.AddField(
            model_name="choice",
            name="question",
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="survey.question"),
        ),
    ]
