# Generated by Django 4.0 on 2022-04-04 00:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("order", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="order",
            old_name="first_name",
            new_name="user_name",
        ),
        migrations.RemoveField(
            model_name="order",
            name="last_name",
        ),
    ]
