# Generated by Django 4.0 on 2022-03-11 11:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("product", "0001_initial"),
        ("user", "0001_initial"),
        ("order", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="orderbasket",
            name="user_id",
            field=models.ForeignKey(
                db_column="user_id",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="order_basket",
                to="user.users",
            ),
        ),
        migrations.AddField(
            model_name="order",
            name="user_id",
            field=models.ForeignKey(
                db_column="user_id", on_delete=django.db.models.deletion.CASCADE, related_name="order", to="user.users"
            ),
        ),
        migrations.AddField(
            model_name="oderproduct",
            name="order_id",
            field=models.ForeignKey(
                db_column="order_id",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="order_product",
                to="order.order",
            ),
        ),
        migrations.AddField(
            model_name="oderproduct",
            name="product_id",
            field=models.ForeignKey(
                db_column="product_id",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="order_product",
                to="product.product",
            ),
        ),
    ]
